version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - "27017:27017"  
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  python-service:
    image: carlotagp/dockerizar:latest
    container_name: python_script
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongoDB:27017
      - DB_NAME=bicis_db 
      - COLLECTION_NAME=bicicorunha 
    networks:
      - app_network
    restart: always 

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
